### ISSUE TITLE
@Nino55N Needs Guidance.

### ISSUE THREAD

**Issue by PhilipRead** [sammygutierrez/movie-list#11]
Have you tried Religion?

**Comment by Nino55N** [comment]
![disco_parrot](https://emoji.slack-edge.com/T039B0HP2/disco_parrot/6f708038175df82b.gif)

**Comment by PhilipRead** [comment]
Make sure you update #7 when you get your problem solved @Nino55N

**Comment by Nino55N** [comment]
halp

**Comment by sammygutierrez** [comment]
Try [this](https://www.noodle.com/guidance-counseling).
