### ISSUE TITLE
Dave thinks he is too good to fix anything

### ISSUE THREAD

**Issue by PhilipRead** [sammygutierrez/movie-list#18]
He's not.

**Comment by mseipel** [comment]
We need a privilege system to lock Dave from making pull requests.  We should put Dave on that.

**Comment by PhilipRead** [comment]
Agreed. Dave make sure Dave does overstep his bounds.

**Comment by dnguyenchevy** [comment]
I'll be right on this.

**Comment by sammygutierrez** [comment]
Status? :beer:

**Comment by Nino55N** [comment]
sup

**Comment by dnguyenchevy** [comment]
he couldn't find his 'fucks'. Still pending.

**Comment by dnguyenchevy** [comment]
lost his 'fucks' sorry. Resolve is not resolve-able.
