### ISSUE TITLE
A new Requirement

### ISSUE THREAD

**Issue by PhilipRead** [sammygutierrez/movie-list#21]
https://www.youtube.com/watch?v=oT4TN57QAb4

**Comment by mseipel** [comment]
https://www.youtube.com/watch?v=goU4uWKlXkA

**Comment by mseipel** [comment]
Requirement Proposal:  All movies must contain http://i.imgur.com/VYz2M.gif

**Comment by PhilipRead** [comment]
Excellent point @mseipel. I'm glad we kept this issue open.

**Comment by mseipel** [comment]
+1 @PhilipRead

**Comment by sammygutierrez** [comment]
![suck a dick](http://media3.giphy.com/media/FX3OLJAUhOZNK/giphy.gif)

**Comment by sammygutierrez** [comment]
Has this issue been resolved?

**Comment by PhilipRead** [comment]
I believe so.
