### ISSUE TITLE
Rewatch Kung Pow with Matt

### ISSUE THREAD

**Issue by mseipel** [sammygutierrez/movie-list#23]
Since I was not informed of the Friday showing of Kung Pow, I declare shenanigans.

**Comment by dnguyenchevy** [comment]
Yeah.... i totally lied, i didn't ask matt.... Totes forgot.

**Comment by mseipel** [comment]
Shenanigans were declared, Dave.  This shit is real.

**Comment by dnguyenchevy** [comment]
maybe we can catch the 2nd one together.

**Comment by mseipel** [comment]
SHENANIGANS WERE DECLARED

**Comment by dnguyenchevy** [comment]
Also, kung pow is in there twice.

**Comment by sammygutierrez** [comment]
go rams
