### ISSUE TITLE
Find Sammy 

### ISSUE THREAD

**Issue by mseipel** [sammygutierrez/movie-list#26]
Title says it all.  Worldwide manhunt initiated.

**Comment by PhilipRead** [comment]
I hate the movie. Finding Nemo was better.

**Comment by mseipel** [comment]
What are your thoughts on Chasing Sammy?

**Comment by sammygutierrez** [comment]
[You can't see me, my time is now!](https://www.youtube.com/watch?v=WnhvR_6oC9s)
