### ISSUE TITLE
Dave needs dat banana yo.

### ISSUE THREAD

**Issue by dnguyenchevy** [sammygutierrez/movie-list#4]
I heard sammy had 2 banana's left. I was wondering if that could be passed downstream to me.

How about it?

**Comment by PhilipRead** [comment]
I don't know, I think we should elevate this issue.

**Comment by dnguyenchevy** [comment]
I need @Nino55N to analyze the risk and hazard of this issue.

**Comment by sammygutierrez** [comment]
Don't feel like sharing anymore. Closed.

**Comment by PhilipRead** [comment]
Sammy, your attitude is no synergistic. I'm reopening this issue I hope you can resolve this.

**Comment by dnguyenchevy** [comment]
Closing issue, I got it.

**Comment by sammygutierrez** [comment]
A 'thanks' would be nice.

**Comment by PhilipRead** [comment]
Let's keep this civil now...

**Comment by dnguyenchevy** [comment]
Thanks Sammy.
