### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by sammygutierrez** [sammygutierrez/movie-list#7]
I want adequate testing so that it can be adequate.

Acceptance criteria: make it adequate

**Comment by PhilipRead** [comment]
Better would take 7 weeks. Can we settle for adequate?

**Comment by sammygutierrez** [comment]
You're right. We don't have that kind of time for this release. Edited original comment.

**Comment by Nino55N** [comment]
@sammygutierrez I need guidance on dis

**Comment by PhilipRead** [comment]
No problem @Nino55N I'll open an issue for you.

**Comment by sammygutierrez** [comment]
Issue #11 has been closed so I am closing this.
